version: '3.8'

services:
  app:
    networks:
      - default
    build: .
    ports:
      - "3000:3000"
    command: sh ./wait-for-sql.sh && npm start
    volumes:
      - ./create_database.sql:/tmp/create_database.sql
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=${DATABASE_URL}
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "tu_base_de_datos"
    ports:
      - "3306:3306"