version: '3.8'
services:
  app:
    build: .
    command: sh ./wait-for-sql.sh
    volumes:
      - ./create_database.sql:/tmp/create_database.sql
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "railway"
    ports:
      - "3306:3306"